In [2]:
import numpy as np

In [3]:
code_size = 3
l_seq = 4
data = np.arange(0, 60).astype(float)
data = data.reshape((-1, l_seq, code_size))
print(data, data.shape)


[[[ 0.  1.  2.]
  [ 3.  4.  5.]
  [ 6.  7.  8.]
  [ 9. 10. 11.]]

 [[12. 13. 14.]
  [15. 16. 17.]
  [18. 19. 20.]
  [21. 22. 23.]]

 [[24. 25. 26.]
  [27. 28. 29.]
  [30. 31. 32.]
  [33. 34. 35.]]

 [[36. 37. 38.]
  [39. 40. 41.]
  [42. 43. 44.]
  [45. 46. 47.]]

 [[48. 49. 50.]
  [51. 52. 53.]
  [54. 55. 56.]
  [57. 58. 59.]]] (5, 4, 3)


In [4]:
print(data[:, :l_seq - 1])
print(data[:, 1:])


[[[ 0.  1.  2.]
  [ 3.  4.  5.]
  [ 6.  7.  8.]]

 [[12. 13. 14.]
  [15. 16. 17.]
  [18. 19. 20.]]

 [[24. 25. 26.]
  [27. 28. 29.]
  [30. 31. 32.]]

 [[36. 37. 38.]
  [39. 40. 41.]
  [42. 43. 44.]]

 [[48. 49. 50.]
  [51. 52. 53.]
  [54. 55. 56.]]]
[[[ 3.  4.  5.]
  [ 6.  7.  8.]
  [ 9. 10. 11.]]

 [[15. 16. 17.]
  [18. 19. 20.]
  [21. 22. 23.]]

 [[27. 28. 29.]
  [30. 31. 32.]
  [33. 34. 35.]]

 [[39. 40. 41.]
  [42. 43. 44.]
  [45. 46. 47.]]

 [[51. 52. 53.]
  [54. 55. 56.]
  [57. 58. 59.]]]


In [5]:
l_win = 3
l_seq = 2
data = np.arange(0,40).astype(float)
data = np.expand_dims(data, axis=-1)
print(data, data.shape)

[[ 0.]
 [ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]
 [11.]
 [12.]
 [13.]
 [14.]
 [15.]
 [16.]
 [17.]
 [18.]
 [19.]
 [20.]
 [21.]
 [22.]
 [23.]
 [24.]
 [25.]
 [26.]
 [27.]
 [28.]
 [29.]
 [30.]
 [31.]
 [32.]
 [33.]
 [34.]
 [35.]
 [36.]
 [37.]
 [38.]
 [39.]] (40, 1)


In [20]:
dataset = []
for i in range(len(data) - (l_win * l_seq) + 1):
    dataset.append(
        data[i: i+(l_win * l_seq)])
dataset = np.array(dataset)
my = dataset.reshape(dataset.shape[0], l_seq, l_win, 1)


In [22]:
print(my.shape)
# lstm_seq = np.expand_dims(lstm_seq, axis=-1)
display(my[1])
print(my[0].shape)


(35, 2, 3, 1)


array([[[1.],
        [2.],
        [3.]],

       [[4.],
        [5.],
        [6.]]])

(2, 3, 1)


In [18]:
for k in range(l_win):
    n_not_overlap_wins = (len(data) - k) // l_win
    n_train_lstm = n_not_overlap_wins - l_seq + 1
    cur_lstm_seq = np.zeros((n_train_lstm, l_seq, l_win))
    for i in range(n_train_lstm):
        cur_seq = np.zeros((l_seq, l_win))
        for j in range(l_seq):
          # print(k,i,j)
          cur_seq[j] = np.squeeze(data[k + l_win* (j+i): k + l_win * (j + i + 1)], axis=-1)
        cur_lstm_seq[i] = cur_seq
    if k == 0:
        lstm_seq = cur_lstm_seq
    else:
        lstm_seq = np.concatenate((lstm_seq, cur_lstm_seq), axis=0)
lstm_seq = np.expand_dims(lstm_seq, axis=-1)


In [23]:
print(lstm_seq.shape)
# lstm_seq = np.expand_dims(lstm_seq, axis=-1)
display(lstm_seq[1])
print(lstm_seq[0].shape)


(35, 2, 3, 1)


array([[[3.],
        [4.],
        [5.]],

       [[6.],
        [7.],
        [8.]]])

(2, 3, 1)


In [64]:
type(data_c[0][0][0])

numpy.ndarray

In [1]:
data_c = data_b.reshape(data_b.shape[0], l_seq, l_win, 1)
# data_c = np.expand_dims(data_c, axis=-1)
print(data_c[0])
print(data_c[0].shape)


NameError: name 'data_b' is not defined

In [61]:
data_b = []
for i in range(len(data) - (l_win * l_seq) + 1):
    data_b.append(data[i: i+(l_win * l_seq)])
data_b = np.array(data_b)
data_c = data_b.reshape(data_b.shape[0], l_seq, l_win, 1)


In [62]:
display(data_b)
print(data_b.shape)


array([[[ 0.],
        [ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.]],

       [[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.]],

       [[ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.]],

       [[ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.]],

       [[ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.]],

       [[ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]],

       [[ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.],
        [11.]],

       [[ 7.],
        [ 8.],
        [ 9.],
        [10.],
        [11.],
        [12.]],

       [[ 8.],
        [ 9.],
        [10.],
        [11.],
        [12.],
        [13.]],

       [[ 9.],
        [10.],
        [11.],
        [12.],
        [13.],
        [14.]],

       [[10.],
        [11.],
        [12.],
        [13.],
        [14.],
     

(35, 6, 1)


In [12]:
data_a = []
for i in range(len(data) - l_win + 1):
    data_a.append(data[i: i+l_win])
data_a = np.array(data_a)

In [13]:
display(data_a)
print(data_a.shape)


array([[[ 0],
        [ 1],
        [ 2]],

       [[ 1],
        [ 2],
        [ 3]],

       [[ 2],
        [ 3],
        [ 4]],

       [[ 3],
        [ 4],
        [ 5]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 5],
        [ 6],
        [ 7]],

       [[ 6],
        [ 7],
        [ 8]],

       [[ 7],
        [ 8],
        [ 9]],

       [[ 8],
        [ 9],
        [10]],

       [[ 9],
        [10],
        [11]],

       [[10],
        [11],
        [12]],

       [[11],
        [12],
        [13]],

       [[12],
        [13],
        [14]],

       [[13],
        [14],
        [15]],

       [[14],
        [15],
        [16]],

       [[15],
        [16],
        [17]],

       [[16],
        [17],
        [18]],

       [[17],
        [18],
        [19]],

       [[18],
        [19],
        [20]],

       [[19],
        [20],
        [21]],

       [[20],
        [21],
        [22]],

       [[21],
        [22],
        [23]],

       [[22],
        [23],
    

(38, 3, 1)
